/** Поля формы «Создать» по справочникам. */
export const CATALOG_CREATE_FIELDS = {
  liabilities: [
    { key: 'template_key', label: 'Ключ', type: 'text', required: true },
    { key: 'title', label: 'Название', type: 'text', required: true },
    { key: 'total_debt', label: 'Сумма долга', type: 'number' },
    { key: 'annual_rate_percent', label: 'Ставка %', type: 'number' },
    { key: 'sort_order', label: 'Порядок', type: 'number' },
    { key: 'is_active', label: 'Активен', type: 'checkbox' },
  ],
  assets: [
    { key: 'template_key', label: 'Ключ', type: 'text', required: true },
    { key: 'title', label: 'Название', type: 'text', required: true },
    { key: 'kind', label: 'Тип', type: 'text' },
    { key: 'asset_value', label: 'Стоимость', type: 'number' },
    { key: 'monthly_maintenance_cost', label: 'Обслуживание/мес', type: 'number' },
    { key: 'monthly_income', label: 'Доход/мес', type: 'number' },
    { key: 'sort_order', label: 'Порядок', type: 'number' },
    { key: 'is_active', label: 'Активен', type: 'checkbox' },
  ],
  starters: [
    { key: 'template_key', label: 'Ключ', type: 'text', required: true },
    { key: 'title', label: 'Название', type: 'text', required: true },
    { key: 'difficulty_rank', label: 'Сложность', type: 'number' },
    { key: 'base_monthly_lifestyle_expense', label: 'База расходов', type: 'number' },
    { key: 'applies_to_save_kind', label: 'Режим', type: 'text' },
    { key: 'sort_order', label: 'Порядок', type: 'number' },
    { key: 'is_active', label: 'Активен', type: 'checkbox' },
    { key: 'blueprint_json', label: 'blueprint_json', type: 'json' },
    { key: 'victory_config_json', label: 'victory_config_json', type: 'json' },
  ],
  events: [
    { key: 'key', label: 'Ключ события', type: 'text', required: true },
    { key: 'title', label: 'Название', type: 'text', required: true },
    { key: 'description', label: 'Описание', type: 'textarea' },
    { key: 'mode', label: 'mode', type: 'text' },
    { key: 'event_slot', label: 'Слот', type: 'select', options: ['period_choice', 'chain_followup', 'macro'] },
    { key: 'content_class', label: 'content_class', type: 'text' },
    { key: 'event_tier', label: 'Tier', type: 'number' },
    { key: 'weight', label: 'Вес', type: 'number' },
    { key: 'repeat_policy', label: 'repeat_policy', type: 'text' },
    { key: 'cooldown_periods', label: 'cooldown_periods', type: 'number' },
    { key: 'mandatory_gate', label: 'mandatory_gate', type: 'text' },
    { key: 'category', label: 'category', type: 'text' },
    { key: 'is_active', label: 'Активен', type: 'checkbox' },
    { key: 'prerequisites_json', label: 'prerequisites_json', type: 'json' },
    { key: 'metadata_json', label: 'metadata_json', type: 'json' },
    { key: 'audience_template_keys', label: 'audience_template_keys', type: 'json' },
  ],
};

export const CATALOG_CREATE_DEFAULTS = {
  liabilities: {
    template_key: '',
    title: '',
    total_debt: 100000,
    annual_rate_percent: 12,
    sort_order: 9999,
    is_active: false,
  },
  assets: {
    template_key: '',
    title: '',
    kind: 'generic',
    asset_value: 1,
    monthly_maintenance_cost: 0,
    monthly_income: 0,
    sort_order: 9999,
    is_active: false,
  },
  starters: {
    template_key: '',
    title: '',
    difficulty_rank: 1,
    base_monthly_lifestyle_expense: 0,
    applies_to_save_kind: 'game',
    sort_order: 9999,
    is_active: false,
    blueprint_json: '{}',
    victory_config_json: '{}',
  },
  events: {
    key: '',
    title: '',
    description: '',
    mode: 'game',
    event_slot: 'period_choice',
    content_class: 'universal',
    event_tier: 1,
    weight: 10,
    repeat_policy: 'repeatable',
    cooldown_periods: 0,
    mandatory_gate: 'none',
    category: '',
    is_active: false,
    prerequisites_json: '{}',
    metadata_json: '{}',
    audience_template_keys: '["all"]',
  },
};
