#!/usr/bin/env bash
set -euo pipefail

ROUND="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(cd "$ROUND/.." && pwd)"
DASH="$(cd "$ROUND/../../dashboard" && pwd)"
OUT="$ROUND/lab-base.css"
REPO_ROOT="$(cd "$ROUND/../../.." && pwd)"
MASCOT_SRC="$REPO_ROOT/design-lab/run-finale/assets/monetka-mascot.png"

sources=(
  "$PARENT/styles.css"
  "$DASH/styles.css"
  "$ROUND/styles.css"
)

{
  cat <<'EOF'
/* Auto-generated by sync-lab.sh — do not edit by hand */
/* Round: analytics/v2-round */

EOF
  for src in "${sources[@]}"; do
    [[ -f "$src" ]] || { echo "missing: $src" >&2; exit 1; }
    cat "$src"
    printf '\n'
  done
} > "$OUT"

mkdir -p "$ROUND/assets"
if [[ -f "$MASCOT_SRC" ]]; then
  cp -f "$MASCOT_SRC" "$ROUND/assets/monetka-mascot.png"
fi

echo "OK: $OUT"
