# Self-contained CSS для dashboard-needs-v5-round (prod parity: .mqx-needs-* из dashboard.css)
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$repoRoot = (Resolve-Path (Join-Path $round "../../..")).Path
$dashLabStyles = Join-Path $round "../../dashboard/styles.css"
$prodDash = Join-Path $repoRoot "frontend-react/src/styles/mqx/dashboard.css"
$out = Join-Path $round "lab-base.css"

function Get-ProdNeedsCss {
    if (-not (Test-Path $prodDash)) {
        Write-Error "Missing prod dashboard.css: $prodDash"
        exit 1
    }
    $lines = Get-Content $prodDash -Encoding utf8
    $start = -1
    $end = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match 'Character needs \(Z-NEEDS\)') { $start = $i; continue }
        if ($start -ge 0 -and $lines[$i] -match 'Bottom sheets \(needs\)') { $end = $i - 1; break }
    }
    if ($start -lt 0 -or $end -lt $start) {
        Write-Error "Could not extract Z-NEEDS section from $prodDash"
        exit 1
    }
  return ($lines[$start..$end] -join "`n")
}

$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path $round "styles.css"),
    $dashLabStyles
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: dashboard-needs-v5-round */
/* Sources: character-needs/styles.css, v5/styles.css, dashboard/styles.css, prod dashboard.css (Z-NEEDS block) */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

"`n/* prod: frontend-react/src/styles/mqx/dashboard.css (Z-NEEDS block) */`n" | Add-Content $out -Encoding utf8
Get-ProdNeedsCss | Add-Content $out -Encoding utf8
"`n" | Add-Content $out -Encoding utf8

$assetSrc = Join-Path $round "../dashboard-needs-round/assets/student-mascot.png"
$assetDst = Join-Path $round "assets/student-mascot.png"
if (-not (Test-Path (Join-Path $round "assets"))) {
    New-Item -ItemType Directory -Path (Join-Path $round "assets") | Out-Null
}
if (Test-Path $assetSrc) {
    Copy-Item $assetSrc $assetDst -Force
}
Write-Host "OK: $out"
