# Self-contained CSS + assets для goal-path-stepper-round
$round = $PSScriptRoot
$dashboard = Join-Path $round ".."
$chainRound = Join-Path $dashboard "goal-chain-round"
$out = Join-Path $round "lab-base.css"
$assets = Join-Path $round "assets"

$sources = @(
    (Join-Path $dashboard "styles.css"),
    (Join-Path $chainRound "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: goal-path-stepper-round */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}
Write-Host "OK: $out"

if (-not (Test-Path $assets)) {
    New-Item -ItemType Directory -Path $assets | Out-Null
}
$pngMascot = Join-Path $dashboard "..\events\assets\monetka-mascot.png"
if (Test-Path $pngMascot) {
    Copy-Item $pngMascot (Join-Path $assets "monetka-mascot.png") -Force
    Write-Host "OK: assets/monetka-mascot.png"
} else {
    Write-Warning "Missing mascot source: $pngMascot"
}
