# Self-contained CSS для pre-game-shell (раунд v2 — полный паритет)
$round = $PSScriptRoot
$parentAuth = Join-Path $round "..\auth-flow"
$parentNg = Join-Path $round "..\new-game-mode"
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $parentAuth "styles.css"),
    (Join-Path $parentNg "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: pre-game-shell v2 */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null

$pngMascot = Join-Path $round "..\events\assets\monetka-mascot.png"
if (Test-Path $pngMascot) {
    Copy-Item $pngMascot (Join-Path $assets "monetka-mascot.png") -Force
    Write-Host "OK: assets/monetka-mascot.png"
}

$pngSit = Join-Path $parentNg "assets\monetka-sit-edge.png"
if (Test-Path $pngSit) {
    Copy-Item $pngSit (Join-Path $assets "monetka-sit-edge.png") -Force
    Write-Host "OK: assets/monetka-sit-edge.png"
}

Write-Host "OK: $out"
