#!/usr/bin/env bash
# Self-contained CSS для persona-portraits-round (bash-only).
set -euo pipefail

ROUND="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME="$(cd "$ROUND/.." && pwd)"
OUT="$ROUND/lab-base.css"
FINANCE_PROD="$(cd "$ROUND/../../../frontend-react/src/styles/mqx" && pwd)/finance.css"

sources=(
  "$THEME/styles.css"
  "$ROUND/styles.css"
)

{
  cat <<'EOF'
/* Auto-generated by sync-lab.sh - do not edit by hand */
/* Round: persona-portraits-round */
/* Sources: game-templates/styles.css, persona-portraits-round/styles.css */

EOF
  for src in "${sources[@]}"; do
    if [[ ! -f "$src" ]]; then
      echo "sync-lab.sh: missing source: $src" >&2
      exit 1
    fi
    cat "$src"
    printf '\n'
  done

  if [[ -f "$FINANCE_PROD" ]]; then
    printf '\n/* --- prod finance.css: scenario picker --- */\n'
    awk '/^\.mqx-scenario-picker/ { p=1 } p { print; if (++n > 220) exit }' "$FINANCE_PROD"
    printf '\n'
  fi
} > "$OUT"

echo "OK: $OUT"
