# Self-contained CSS для hero-no-timer-round
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: hero-no-timer-round */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}
Write-Host "OK: $out"
