# Self-contained CSS — pre-game-playful-v3
$round = $PSScriptRoot
$repo = Split-Path (Split-Path $round -Parent) -Parent
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $round "..\type-scale-round\styles.css"),
    (Join-Path $round "..\auth-flow\styles.css"),
    (Join-Path $round "..\new-game-mode\styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit */
/* Round: pre-game-playful-v3 */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null

@(
    @{ Src = Join-Path $round "..\events\assets\monetka-mascot.png"; Dst = "monetka-mascot.png" },
    @{ Src = Join-Path $round "..\new-game-mode\assets\monetka-sit-edge.png"; Dst = "monetka-sit-edge.png" },
    @{ Src = Join-Path $repo "landing\public\brand\logo-full.png"; Dst = "logo-full.png" }
) | ForEach-Object {
    if (Test-Path $_.Src) {
        Copy-Item $_.Src (Join-Path $assets $_.Dst) -Force
        Write-Host "OK: assets/$($_.Dst)"
    }
}

Write-Host "OK: $out"
