# Self-contained CSS — pre-game-playful-v3 (atomic write, UTF-8 no BOM)
$round = $PSScriptRoot
$repo = Split-Path (Split-Path $round -Parent) -Parent
$out = Join-Path $round "lab-base.css"
$tmp = Join-Path $round "lab-base.css.tmp"

$sources = @(
    (Join-Path $round "..\type-scale-round\styles.css"),
    (Join-Path $round "..\auth-flow\styles.css"),
    (Join-Path $round "..\new-game-mode\styles.css"),
    (Join-Path $round "..\game-templates\styles.css"),
    (Join-Path $round "styles.css")
)

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Auto-generated by sync-lab.ps1 - do not edit */")
[void]$sb.AppendLine("/* Round: pre-game-playful-v3 */")
[void]$sb.AppendLine("")

foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    [void]$sb.AppendLine((Get-Content $src -Raw -Encoding UTF8))
    [void]$sb.AppendLine("")
}

[System.IO.File]::WriteAllText($tmp, $sb.ToString(), $utf8NoBom)
if (Test-Path $out) { Remove-Item $out -Force -ErrorAction SilentlyContinue }
Move-Item $tmp $out -Force

$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null

@(
    @{ Src = Join-Path $round "..\events\assets\monetka-mascot.png"; Dst = "monetka-mascot.png" },
    @{ Src = Join-Path $round "..\new-game-mode\assets\monetka-sit-edge.png"; Dst = "monetka-sit-edge.png" },
    @{ Src = Join-Path $round "..\..\landing\public\brand\logo-full.png"; Dst = "logo-full.png" }
) | ForEach-Object {
    if (Test-Path $_.Src) {
        Copy-Item $_.Src (Join-Path $assets $_.Dst) -Force
        Write-Host "OK: assets/$($_.Dst)"
    }
}

Write-Host "OK: $out ($((Get-Item $out).Length) bytes)"
