-- Цель tutorial_invest: новый заголовок и порядок до safety_3x/6x (см. victory_seeds.py)

UPDATE game_starter_templates
SET victory_config_json = '{"schema_version": 1, "min_period_index_for_victory": 7, "required_goals_met": 5, "progression_mode": "chain", "goals": [{"key": "tutorial_salary", "type": "action_once", "title": "Забрать зарплату", "action": "salary_claimed", "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "tutorial_cushion", "type": "action_once", "title": "Внести в подушку", "action": "safety_contributed", "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "tutorial_invest", "type": "action_once", "title": "Положить деньги на депозит или купить облигацию", "action": "invest_opened", "requires_mechanics": ["capital_invest"], "required": false, "enabled": true}, {"key": "safety_3x", "type": "safety_fund_months", "title": "Подушка ≥ 3× обязательств", "months_multiplier": 3, "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "invest_income_15k", "type": "passive_income_monthly_min", "title": "Доход с инвестиций ≥ 15 000 ₽/мес", "min_monthly": 15000, "requires_mechanics": ["capital_invest"], "required": false, "enabled": true}], "playtest_mode": "tutorial"}'
WHERE template_key = 'mq_game_basic_v1';

UPDATE game_starter_templates
SET victory_config_json = '{"schema_version": 1, "min_period_index_for_victory": 7, "required_goals_met": 7, "progression_mode": "chain", "goals": [{"key": "tutorial_salary", "type": "action_once", "title": "Забрать зарплату", "action": "salary_claimed", "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "tutorial_cushion", "type": "action_once", "title": "Внести в подушку", "action": "safety_contributed", "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "tutorial_invest", "type": "action_once", "title": "Положить деньги на депозит или купить облигацию", "action": "invest_opened", "requires_mechanics": ["capital_invest"], "required": false, "enabled": true}, {"key": "safety_6x", "type": "safety_fund_months", "title": "Подушка ≥ 6× обязательств", "months_multiplier": 6, "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "invest_income_80k", "type": "passive_income_monthly_min", "title": "Доход с инвестиций ≥ 80 000 ₽/мес", "min_monthly": 80000, "requires_mechanics": ["capital_invest"], "required": false, "enabled": true}, {"key": "tutorial_insurance", "type": "action_once", "title": "Оформить страховку", "action": "insurance_purchased", "requires_mechanics": ["capital_insurance"], "required": false, "enabled": true}, {"key": "cash_10m", "type": "cash_balance_min", "title": "Наличные ≥ 10 000 000 ₽", "min_cash": 10000000, "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}], "playtest_mode": "tutorial"}'
WHERE template_key IN ('mq_game_tight_budget_v1', 'mq_game_mortgage_stress_v1');

UPDATE game_starter_templates
SET victory_config_json = '{"schema_version": 1, "min_period_index_for_victory": 7, "required_goals_met": 7, "progression_mode": "chain", "goals": [{"key": "tutorial_salary", "type": "action_once", "title": "Забрать зарплату", "action": "salary_claimed", "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "tutorial_cushion", "type": "action_once", "title": "Внести в подушку", "action": "safety_contributed", "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "tutorial_invest", "type": "action_once", "title": "Положить деньги на депозит или купить облигацию", "action": "invest_opened", "requires_mechanics": ["capital_invest"], "required": false, "enabled": true}, {"key": "safety_6x", "type": "safety_fund_months", "title": "Подушка ≥ 6× обязательств", "months_multiplier": 6, "requires_mechanics": ["dashboard_core"], "required": false, "enabled": true}, {"key": "invest_income_80k", "type": "passive_income_monthly_min", "title": "Доход с инвестиций ≥ 80 000 ₽/мес", "min_monthly": 80000, "requires_mechanics": ["capital_invest"], "required": false, "enabled": true}, {"key": "tutorial_insurance", "type": "action_once", "title": "Оформить страховку", "action": "insurance_purchased", "requires_mechanics": ["capital_insurance"], "required": false, "enabled": true}, {"key": "rental_home_owned", "type": "asset_kind_any_owned", "title": "Сдаваемая квартира в собственности", "asset_kinds_any": ["rental_home", "rental_house", "rental_mansion"], "requires_mechanics": ["capital_property"], "required": false, "enabled": true}], "playtest_mode": "tutorial"}'
WHERE template_key = 'mq_game_debt_stack_v1';
