# Self-contained CSS for states-icons-round
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path $round "styles.css")
)

$header = "/* Auto-generated by sync-lab.ps1 - do not edit by hand */`n/* Round: states-icons-round */`n`n"
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null
$png = Join-Path $parent "..\events\assets\monetka-mascot.png"
if (-not (Test-Path $png)) {
    $png = Join-Path $parent "..\game-ui\juice-round\assets\monetka-mascot.png"
}
if (Test-Path $png) {
    Copy-Item $png (Join-Path $assets "monetka-mascot.png") -Force
    Write-Host "OK: assets/monetka-mascot.png"
} else {
    Write-Warning "monetka-mascot.png not found"
}

Write-Host "OK: $out"
