# Self-contained CSS для details-actions-round
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$actionsRound = Join-Path $parent "actions-round"
$out = Join-Path $round "lab-base.css"

$investStyles = Join-Path (Join-Path (Join-Path $parent "..") "invest-forms") "styles.css"
$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path (Join-Path $parent "flows-round") "styles.css"),
    (Join-Path (Join-Path $parent "orient-round") "styles.css"),
    (Join-Path $actionsRound "styles.css"),
    $investStyles,
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: details-actions-round */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}
Write-Host "OK: $out"
