#!/usr/bin/env bash
# Self-contained CSS для details-actions-round (bash-only, без PowerShell).
set -euo pipefail

ROUND="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(cd "$ROUND/.." && pwd)"
OUT="$ROUND/lab-base.css"

# capital-page base + flows + этот раунд (без invest-forms / actions-round — ломают body и lab-header)
sources=(
  "$PARENT/styles.css"
  "$PARENT/flows-round/styles.css"
  "$ROUND/styles.css"
)

{
  cat <<'EOF'
/* Auto-generated by sync-lab.sh - do not edit by hand */
/* Round: details-actions-round */
/* Sources: ../styles.css, ../flows-round/styles.css, styles.css */

EOF
  for src in "${sources[@]}"; do
    if [[ ! -f "$src" ]]; then
      echo "sync-lab.sh: missing source: $src" >&2
      exit 1
    fi
    cat "$src"
    printf '\n'
  done
} > "$OUT"

echo "OK: $OUT"
