# Self-contained CSS для game-ui/juice-round
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 - do not edit by hand */
/* Round: juice-round */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null
$srcPng = Join-Path $parent "..\events\layout-round\assets\monetka-mascot.png"
if (-not (Test-Path $srcPng)) {
    $srcPng = Join-Path $parent "..\onboarding-guided\assets\monetka-mascot.png"
}
if (Test-Path $srcPng) {
    Copy-Item $srcPng (Join-Path $assets "monetka-mascot.png") -Force
    Write-Host "OK: assets/monetka-mascot.png"
} else {
    Write-Warning "monetka-mascot.png source not found - add to assets/ manually"
}

Write-Host "OK: $out"
