# Self-contained CSS для section-header-a-page-round
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: section-header-a-page-round */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

# Assets (Monetka)
$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null
$png = Join-Path $parent "goal-chain-round\assets\monetka-mascot.png"
Copy-Item $png (Join-Path $assets "monetka-mascot.png") -Force

Write-Host "OK: $out"
Write-Host "OK: assets/monetka-mascot.png"

