# Self-contained CSS для section-header-a-page-round
$round = $PSScriptRoot
$parent = Join-Path $round ".."
$out = Join-Path $round "lab-base.css"
$tmp = Join-Path $round "lab-base.css.tmp"

$needsRound = Join-Path $parent "..\\character-needs\\dashboard-needs-round"

$sources = @(
    (Join-Path $parent "styles.css"),
    (Join-Path $needsRound "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: section-header-a-page-round */

"@
Set-Content $tmp $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $tmp -Encoding utf8
    "`n" | Add-Content $tmp -Encoding utf8
}

# Replace output atomically (avoids "file is used by another process" issues on Windows)
Move-Item -Force $tmp $out

# Assets (Monetka)
$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null
$png = Join-Path $parent "goal-chain-round\assets\monetka-mascot.png"
Copy-Item $png (Join-Path $assets "monetka-mascot.png") -Force

# Assets (Needs mascot)
$student = Join-Path $needsRound "assets\student-mascot.png"
Copy-Item $student (Join-Path $assets "student-mascot.png") -Force

Write-Host "OK: $out"
Write-Host "OK: assets/monetka-mascot.png"
Write-Host "OK: assets/student-mascot.png"

