#!/usr/bin/env bash
set -euo pipefail
ROUND="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(cd "$ROUND/.." && pwd)"
REPO_ROOT="$(cd "$ROUND/../../.." && pwd)"
PROD_DASH="$REPO_ROOT/frontend-react/src/styles/mqx/dashboard.css"
OUT="$ROUND/lab-base.css"

extract_needs_css() {
  awk '
    /Character needs \(Z-NEEDS\)/ { on=1 }
    /Bottom sheets \(needs\)/ { if (on) exit }
    on { print }
  ' "$PROD_DASH"
}

sources=(
  "$PARENT/styles.css"
  "$ROUND/styles.css"
  "$PARENT/../dashboard/styles.css"
)

{
  cat <<'EOF'
/* Auto-generated by sync-lab.sh — do not edit by hand */
/* Round: dashboard-needs-v7-round */

EOF
  for src in "${sources[@]}"; do
    [[ -f "$src" ]] || { echo "missing: $src" >&2; exit 1; }
    cat "$src"
    printf '\n'
  done
  printf '\n/* prod: dashboard.css (Z-NEEDS) */\n'
  extract_needs_css
  printf '\n'
} > "$OUT"

mkdir -p "$ROUND/assets"
PORTRAIT_SRC="$REPO_ROOT/design-lab/game-templates/persona-portraits-round/assets/student-mascot-dash.png"
if [[ -f "$PORTRAIT_SRC" ]]; then
  cp -f "$PORTRAIT_SRC" "$ROUND/assets/student-mascot-dash.png"
fi
echo "OK: $OUT"
