"""Каталог стартовых шаблонов Game (идемпотентный upsert в main.ensure_schema_compatibility)."""

# Сортируется sort_order; ON CONFLICT не обновляет существующие строки.
GAME_STARTER_TEMPLATE_SEEDS = [
    {
        "template_key": "mq_game_basic_v1",
        "title": "Студент",
        "difficulty_rank": 1,
        "base_expense": 37500.0,
        "sort_order": 10,
        "blueprint": {
            "description": "Первый бюджет без долгов и без жилья в старте — еда, транспорт, досуг; жильё выбираешь в игре.",
            "scenario_icon": "fresh_start",
            "compare_note": "Зарплата ~62,5k, жизнь ~37,5k (без аренды), свободно ~25k.",
            "highlights": [
                "Доход ~62 500 ₽/мес",
                "Расходы на жизнь ~37 500 ₽/мес (без жилья)",
                "Свободно ~25 000 ₽/мес",
                "Без долгов и активов в старте",
                "На счёте ~15 000 ₽",
            ],
            "period_duration_seconds": 300,
            "cash_balance": 15000,
            "monthly_salary": 62500,
            "assets": [],
            "liabilities": [],
            "mechanics": {
                "capital_invest": True,
                "capital_insurance": False,
                "capital_property": False,
                "capital_liabilities": False,
            },
            "mechanics_unlock": [
                {"after_goal": None, "grant": ["capital_flows", "capital_invest"]},
            ],
        },
    },
    {
        "template_key": "mq_game_tight_budget_v1",
        "title": "Профессионал",
        "difficulty_rank": 2,
        "base_expense": 27500.0,
        "sort_order": 20,
        "blueprint": {
            "description": "Студия в аренде, машина и автокредит — жильё и авто как отдельные платежи, не в burn.",
            "scenario_icon": "car_loan",
            "compare_note": "Аренда студии 22,5+5k, авто 18k + кредит ~12k, жизнь ~27,5k.",
            "highlights": [
                "Доход ~100 000 ₽/мес",
                "Аренда студии ~27 500 ₽/мес",
                "Авто + кредит ~30 000 ₽/мес",
                "Расходы на жизнь ~27 500 ₽/мес",
                "Свободно ~15 000 ₽/мес",
                "На счёте ~25 000 ₽",
            ],
            "period_duration_seconds": 300,
            "cash_balance": 25000,
            "monthly_salary": 100000,
            "assets": [
                {
                    "title": "Студия (аренда)",
                    "kind": "leased_dwelling",
                    "asset_value": 0,
                    "monthly_maintenance_cost": 27500,
                    "monthly_income": 0,
                },
                {
                    "title": "Личная машина",
                    "kind": "car_personal",
                    "asset_value": 1200000,
                    "monthly_maintenance_cost": 18000,
                    "monthly_income": 0,
                },
            ],
            "liabilities": [
                {
                    "title": "Автокредит",
                    "total_debt": 900000,
                    "annual_rate_percent": 16,
                },
            ],
            "mechanics_unlock": [
                {"after_goal": None, "grant": ["capital_flows"]},
                {"after_goal": "tutorial_cushion", "grant": ["capital_liabilities", "capital_invest"]},
                {"after_goal": "tutorial_invest", "grant": ["capital_insurance"]},
                {"after_goal": "tutorial_insurance", "grant": ["capital_property"]},
            ],
        },
    },
    {
        "template_key": "mq_game_mortgage_stress_v1",
        "title": "Руководитель",
        "difficulty_rank": 3,
        "base_expense": 43625.0,
        "sort_order": 30,
        "blueprint": {
            "description": "Своя 2-комнатная, ипотека, два авто — содержание квартиры отдельно от burn.",
            "scenario_icon": "home_mortgage",
            "compare_note": "Квартира 10 млн, содержание 30k, ипотека ~30k, два авто 36k.",
            "highlights": [
                "Доход ~150 000 ₽/мес",
                "2-комнатная + ипотека ~2,7 млн",
                "Содержание квартиры ~30 000 ₽/мес",
                "Два авто ~36 000 ₽/мес",
                "Расходы на жизнь ~43 600 ₽/мес",
                "Свободно ~10 000 ₽/мес",
                "На счёте ~35 000 ₽",
            ],
            "period_duration_seconds": 300,
            "cash_balance": 35000,
            "monthly_salary": 150000,
            "assets": [
                {
                    "title": "2-комнатная квартира",
                    "kind": "home",
                    "asset_value": 10000000,
                    "monthly_maintenance_cost": 30000,
                    "monthly_income": 0,
                },
                {
                    "title": "Семейный автомобиль",
                    "kind": "car_personal",
                    "asset_value": 1200000,
                    "monthly_maintenance_cost": 18000,
                    "monthly_income": 0,
                },
                {
                    "title": "Второй автомобиль",
                    "kind": "car_personal",
                    "asset_value": 1200000,
                    "monthly_maintenance_cost": 18000,
                    "monthly_income": 0,
                },
            ],
            "liabilities": [
                {
                    "title": "Ипотека",
                    "total_debt": 2700000,
                    "annual_rate_percent": 13.5,
                },
            ],
            "mechanics_unlock": [
                {"after_goal": None, "grant": ["capital_flows"]},
                {"after_goal": "tutorial_cushion", "grant": ["capital_liabilities", "capital_invest"]},
                {"after_goal": "tutorial_invest", "grant": ["capital_insurance"]},
                {"after_goal": "tutorial_insurance", "grant": ["capital_property"]},
            ],
        },
    },
    {
        "template_key": "mq_game_debt_stack_v1",
        "title": "Предприниматель",
        "difficulty_rank": 4,
        "base_expense": 91250.0,
        "sort_order": 40,
        "blueprint": {
            "description": "Ипотека на 2-комнатную, два авто и карта — без доходной недвижимости в старте.",
            "scenario_icon": "factory",
            "compare_note": "Максимум долгов и авто; free flow около нуля.",
            "highlights": [
                "Доход ~200 000 ₽/мес",
                "2-комнатная, ипотека ~3,8 млн",
                "Два авто + кредитная карта",
                "Расходы на жизнь ~91 250 ₽/мес",
                "Свободно ~−3 000 ₽/мес",
                "На счёте ~45 000 ₽",
            ],
            "period_duration_seconds": 300,
            "cash_balance": 45000,
            "monthly_salary": 200000,
            "assets": [
                {
                    "title": "2-комнатная квартира",
                    "kind": "home",
                    "asset_value": 10000000,
                    "monthly_maintenance_cost": 30000,
                    "monthly_income": 0,
                },
                {
                    "title": "Автомобиль",
                    "kind": "car_personal",
                    "asset_value": 1200000,
                    "monthly_maintenance_cost": 18000,
                    "monthly_income": 0,
                },
                {
                    "title": "Второй автомобиль",
                    "kind": "car_personal",
                    "asset_value": 1200000,
                    "monthly_maintenance_cost": 18000,
                    "monthly_income": 0,
                },
            ],
            "liabilities": [
                {
                    "title": "Ипотека",
                    "total_debt": 3800000,
                    "annual_rate_percent": 13.5,
                },
                {
                    "title": "Кредитная карта",
                    "total_debt": 150000,
                    "annual_rate_percent": 24,
                },
            ],
            "mechanics_unlock": [
                {"after_goal": None, "grant": ["capital_flows"]},
                {"after_goal": "tutorial_cushion", "grant": ["capital_liabilities", "capital_invest"]},
                {"after_goal": "tutorial_invest", "grant": ["capital_insurance"]},
                {"after_goal": "tutorial_insurance", "grant": ["capital_property"]},
            ],
        },
    },
]
