# Self-contained CSS для type-scale-round
$round = $PSScriptRoot
$dash = Join-Path $round "..\dashboard"
$period = Join-Path $dash "period-actions-round"
$out = Join-Path $round "lab-base.css"

$sources = @(
    (Join-Path $dash "styles.css"),
    (Join-Path $period "styles.css"),
    (Join-Path $round "styles.css")
)

$header = @"
/* Auto-generated by sync-lab.ps1 — do not edit by hand */
/* Round: type-scale-round */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}
Write-Host "OK: $out"
