#!/usr/bin/env bash
# Собрать self-contained CSS + assets для одного раунда design-lab/events/*
set -euo pipefail

ROUND="$(cd "${1:?usage: sync-lab-round.sh <round-dir>}" && pwd)"
WITH_LAYOUT="${2:-}"

ROUND_LEAF="$(basename "$ROUND")"
EVENTS="$(cd "$ROUND/.." && pwd)"
OUT="$ROUND/lab-base.css"

sources=(
  "$EVENTS/styles.css"
  "$EVENTS/styles-monetka.css"
)

include_layout=0
if [[ "$WITH_LAYOUT" == "--with-layout" ]]; then
  include_layout=1
elif [[ "$ROUND_LEAF" != "layout-round" ]] && [[ -f "$ROUND/index.html" ]] && grep -q 'ev-l3__' "$ROUND/index.html"; then
  include_layout=1
fi

if [[ "$include_layout" -eq 1 ]]; then
  sources+=("$EVENTS/layout-round/styles.css")
fi

labels=()
for src in "${sources[@]}"; do
  if [[ ! -f "$src" ]]; then
    echo "sync-lab-round.sh: missing source: $src" >&2
    exit 1
  fi
  labels+=("${src#$EVENTS/}")
done

{
  cat <<EOF
/* Auto-generated by sync-lab-round.sh - do not edit by hand */
/* Round: $ROUND_LEAF */
/* Sources: $(IFS=,; echo "${labels[*]}") */

EOF
  for src in "${sources[@]}"; do
    cat "$src"
    printf '\n'
  done
} > "$OUT"

mkdir -p "$ROUND/assets"
cp -f "$EVENTS/assets/monetka-mascot.png" "$ROUND/assets/monetka-mascot.png"

echo "OK: $OUT"
echo "OK: assets/monetka-mascot.png"
