# Собрать self-contained CSS + assets для одного раунда design-lab/events/*
# npx serve . отдаёт только текущую папку — пути ../ ломаются (404).
param(
    [Parameter(Mandatory = $true)]
    [string]$RoundDir,
    [switch]$WithLayoutStyles
)

$round = Resolve-Path $RoundDir
$events = Join-Path $round ".."
$shared = $PSScriptRoot
$out = Join-Path $round "lab-base.css"
$sources = @(
    (Join-Path $events "styles.css"),
    (Join-Path $events "styles-monetka.css")
)
if ($WithLayoutStyles) {
    $sources += (Join-Path $events "layout-round\styles.css")
}

$header = @"
/* Auto-generated by sync-lab-round.ps1 — do not edit by hand */
/* Round: $(Split-Path $round -Leaf) */
/* Sources: $(($sources | ForEach-Object { Split-Path $_ -Leaf }) -join ', ') */

"@
Set-Content $out $header -Encoding utf8
foreach ($src in $sources) {
    if (-not (Test-Path $src)) {
        Write-Error "Missing source: $src"
        exit 1
    }
    Get-Content $src -Raw | Add-Content $out -Encoding utf8
    "`n" | Add-Content $out -Encoding utf8
}

$assets = Join-Path $round "assets"
New-Item -ItemType Directory -Force -Path $assets | Out-Null
$png = Join-Path $events "assets\monetka-mascot.png"
Copy-Item $png (Join-Path $assets "monetka-mascot.png") -Force

Write-Host "OK: $out"
Write-Host "OK: assets/monetka-mascot.png"
